name: deploying Hexo project to GitHub pages
on:
  [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }}
          PUBLISH_REPOSITORY: cys2004/cys2004.github.io
          BRANCH: main
          PUBLISH_DIR: ./public